import { SquareSet } from './square-set.js';
import type { Color, Piece, Square } from './types.js';
export declare function kingAttacks(square: Square): SquareSet;
export declare function knightAttacks(square: Square, color: Color): SquareSet;
export declare function silverAttacks(square: Square, color: Color): SquareSet;
export declare function goldAttacks(square: Square, color: Color): SquareSet;
export declare function pawnAttacks(square: Square, color: Color): SquareSet;
export declare function bishopAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function rookAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function lanceAttacks(square: Square, color: Color, occupied: SquareSet): SquareSet;
export declare function horseAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function dragonAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function goBetweenAttacks(square: Square): SquareSet;
export declare function chariotAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function sideMoverAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function verticalMoverAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function copperAttacks(square: Square, color: Color): SquareSet;
export declare function leopardAttacks(square: Square): SquareSet;
export declare function tigerAttacks(square: Square, color: Color): SquareSet;
export declare function elephantAttacks(square: Square, color: Color): SquareSet;
export declare function kirinAttacks(square: Square): SquareSet;
export declare function phoenixAttacks(square: Square): SquareSet;
export declare function queenAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function stagAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function oxAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function boarAttacks(square: Square, occupied: SquareSet): SquareSet;
export declare function whaleAttacks(square: Square, color: Color, occupied: SquareSet): SquareSet;
export declare function whiteHorseAttacks(square: Square, color: Color, occupied: SquareSet): SquareSet;
export declare function falconLionAttacks(square: Square, color: Color): SquareSet;
export declare function falconAttacks(square: Square, color: Color, occupied: SquareSet): SquareSet;
export declare function eagleLionAttacks(square: Square, color: Color): SquareSet;
export declare function eagleAttacks(square: Square, color: Color, occupied: SquareSet): SquareSet;
export declare function lionAttacks(square: Square): SquareSet;
export declare function attacks(piece: Piece, square: Square, occupied: SquareSet): SquareSet;
export declare function ray(a: Square, b: Square): SquareSet;
export declare function between(a: Square, b: Square): SquareSet;
//# sourceMappingURL=attacks.d.ts.map