var YaneuraOu_K_P=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var f=moduleArg,ba=!!globalThis.window,m=!!globalThis.WorkerGlobalScope,p=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,r=m&&self.name?.startsWith("em-pthread");if(p){var ca=require("worker_threads");global.Worker=ca.Worker;r=(m=!ca.tb)&&"em-pthread"==ca.workerData}
(function(){function a(){var g=d.shift();if(!b&&void 0!==g){if("quit"===g)return f.terminate();var h=f.ccall("usi_command","number",["string"],[g]);h&&d.unshift(g);e=h?2*e:1;setTimeout(a,e)}}var b=!1,c=[];f.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var h=0;h<c.length;h++)c[h](g)})};f.addMessageListener=function(g){c.push(g)};f.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};f.terminate=function(){b=!0;t.xa()};var d=[],e=1;f.postMessage=function(g){d.push(g)};
f.postRun=function(){f.postMessage=function(g){d.push(g);1===d.length&&a()};a()}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:m&&(_scriptName=self.location.href);var ha="",ia,ja;
if(p){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||m){try{ha=(new URL(".",_scriptName)).href}catch{}p||(m&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>
{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);})}var ma=console.log.bind(console),na=console.error.bind(console);if(p){var oa=require("util"),pa=a=>"object"==typeof a?oa.inspect(a):a;ma=(...a)=>fs.writeSync(1,a.map(pa).join(" ")+"\n");na=(...a)=>fs.writeSync(2,a.map(pa).join(" ")+"\n")}var qa=ma,u=na,ra,sa=!1,ta,ka=a=>a.startsWith("file://");function w(){y.buffer!=z.buffer&&ua()}var va,wa;
if(p&&r){var xa=ca.parentPort;xa.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>xa.postMessage(a)});process.on("uncaughtException",a=>{postMessage({D:"uncaughtException",error:a});process.exit(1)})}var ya;
if(r){var za=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.D;if("load"===d){let e=[];self.onmessage=g=>e.push(g);ya=()=>{postMessage({D:"loaded"});for(let g of e)a(g);self.onmessage=a};for(const g of c.Ka)if(!f[g]||f[g].proxy)f[g]=(...h)=>{postMessage({D:"callHandler",Ja:g,args:h})},"print"==g&&(qa=f[g]),"printErr"==g&&(u=f[g]);y=c.Xa;ua();ra=c.Ya;Aa();Ba()}else if("run"===d){Ca(c.B);Da(c.B,0,0,1,0,0);Ea();Fa(c.B);za||=!0;try{Ga(c.Ua,c.Y)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?za&&Ha():d&&(u(`worker: received unknown command ${d}`),u(c)))}catch(e){throw Ia(),e;}}self.onmessage=a}var z,Ja,Ka,A,C,La,D,Ma=!1;function ua(){var a=y.buffer;z=new Int8Array(a);Ka=new Int16Array(a);Ja=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);C=new Uint32Array(a);new Float32Array(a);La=new Float64Array(a);D=new BigInt64Array(a);new BigUint64Array(a)}
function Na(){Ma=!0;r?ya():(f.noFSInit||F.da||F.V(),G.__wasm_call_ctors(),F.oa=!1)}function I(a){a="Aborted("+a+")";u(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");wa?.(a);throw a;}var Oa;async function Pa(a){try{var b=await ia(a);return new Uint8Array(b)}catch{}if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Qa(a,b){try{var c=await Pa(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function Ra(a){var b=Oa;if(!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return Qa(b,a)}
function Sa(){Ta={__pthread_create_js:Ua,__syscall_fcntl64:Va,__syscall_getcwd:Wa,__syscall_ioctl:Xa,__syscall_openat:Ya,_abort_js:Za,_emscripten_init_main_thread_js:$a,_emscripten_notify_mailbox_postmessage:ab,_emscripten_receive_on_main_thread_js:bb,_emscripten_runtime_keepalive_clear:cb,_emscripten_thread_cleanup:db,_emscripten_thread_mailbox_await:Fa,_emscripten_thread_set_strongref:eb,_setitimer_js:fb,_tzset_js:gb,clock_time_get:hb,emscripten_check_blocking_allowed:ib,emscripten_date_now:jb,
emscripten_exit_with_live_runtime:kb,emscripten_get_now:lb,emscripten_resize_heap:mb,environ_get:nb,environ_sizes_get:ob,exit:pb,fd_close:qb,fd_read:rb,fd_seek:sb,fd_write:tb,memory:y,proc_exit:ub};return{env:Ta,wasi_snapshot_preview1:Ta}}
async function Aa(){function a(c,d){G=c.exports;G=vb();t.ya.push(G._emscripten_tls_init);c=G;wb=f._main=c.__main_argc_argv;f._usi_command=c.usi_command;xb=c.pthread_self;Da=c._emscripten_thread_init;Ia=c._emscripten_thread_crashed;yb=c._emscripten_run_js_on_main_thread;zb=c._emscripten_thread_free_data;Ab=c._emscripten_thread_exit;Bb=c._emscripten_timeout;Cb=c._emscripten_check_mailbox;Db=c.emscripten_stack_set_limits;Eb=c._emscripten_stack_restore;Fb=c._emscripten_stack_alloc;Gb=c.emscripten_stack_get_current;
Hb=c.__indirect_function_table;ra=d;return G}var b=Sa();if(r)return b=new WebAssembly.Instance(ra,Sa()),a(b,ra);Oa??=ha+"yaneuraou.k-p.wasm";return function(c){return a(c.instance,c.module)}(await Ra(b))}class Ib{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Jb=a=>{a.terminate();a.onmessage=()=>{}},Kb=[],J=0,Lb=null,Mb=()=>{J--;if(0==J&&Lb){var a=Lb;Lb=null;a()}},Ob=a=>{0==t.L.length&&(Nb(),t.ra(t.L[0]));var b=t.L.pop();if(!b)return 6;t.T.push(b);t.K[a.B]=b;b.B=a.B;var c={D:"run",Ua:a.Ta,Y:a.Y,B:a.B};p&&b.unref();b.postMessage(c,a.za);return 0},K=0,L=(a,b,...c)=>{for(var d=2*c.length,e=Gb(),g=Fb(8*d),h=g>>>3,l=0;l<c.length;l++){var n=c[l];"bigint"==typeof n?((w(),D)[h+2*l>>>0]=1n,(w(),D)[h+2*l+1>>>0]=n):((w(),D)[h+2*l>>>0]=0n,(w(),La)[h+2*l+1>>>0]=
n)}a=yb(a,0,d,g,b);Eb(e);return a};function ub(a){if(r)return L(0,1,a);ta=a;M||0<K||(t.xa(),sa=!0);fa(a,new Ib(a))}function Pb(a){if(r)return L(1,0,a);pb(a)}var pb=a=>{ta=a;if(r)throw Pb(a),"unwind";ub(a)};function Ea(){t.ya.forEach(a=>a())}function Qb(){for(var a=(navigator.hardwareConcurrency||4)-1;a--;)Nb();Kb.push(async()=>{var b=Rb();J++;await b;Mb()})}function Nb(){var a=new Worker(_scriptName,{workerData:"em-pthread",name:"em-pthread"});t.L.push(a)}
async function Rb(){if(!r)return Promise.all(t.L.map(t.ra))}
var t={L:[],T:[],ya:[],K:{},V(){r||Qb()},xa:()=>{for(var a of t.T)Jb(a);for(a of t.L)Jb(a);t.L=[];t.T=[];t.K={}},ua:a=>{var b=a.B;delete t.K[b];t.L.push(a);t.T.splice(t.T.indexOf(a),1);a.B=0;zb(b)},ra:a=>new Promise(b=>{a.onmessage=g=>{var h=g.data;g=h.D;if(h.X&&h.X!=xb()){var l=t.K[h.X];l?l.postMessage(h,h.za):u(`Internal error! Worker sent a message "${g}" to target pthread ${h.X}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ha();else if("spawnThread"===g)Ob(h);else if("cleanupThread"===
g)Sb(()=>{t.ua(t.K[h.Va])});else if("loaded"===g)a.loaded=!0,p&&!a.B&&a.unref(),b(a);else if("setimmediate"===h.target)a.postMessage(h);else if("uncaughtException"===g)a.onerror(h.error);else if("callHandler"===g)f[h.Ja](...h.args);else g&&u(`worker sent an unknown command ${g}`)};a.onerror=g=>{u(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};p&&(a.on("message",g=>a.onmessage({data:g})),a.on("error",g=>a.onerror(g)));var c=[],d=["print"],e;for(e of d)f.propertyIsEnumerable(e)&&
c.push(e);a.postMessage({D:"load",Ka:c,Xa:y,Ya:ra})})},Tb=[];function Ca(a){var b=(w(),C)[a+52>>>2>>>0];a=(w(),C)[a+56>>>2>>>0];Db(b,b-a);Eb(b)}var Ub=[],Ga=(a,b)=>{M=K=0;var c=Ub[a];c||(Ub[a]=c=Hb.get(a));a=c(b);M||0<K?ta=a:Ab(a)},M=!0,y;function Vb(a,b,c,d){return r?L(2,1,a,b,c,d):Ua(a,b,c,d)}
function Ua(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return Vb(a,b,c,d);a={Ta:c,B:a,Y:d,za:e};return r?(a.D="spawnThread",postMessage(a,e),0):Ob(a)}
var N=()=>{var a=(w(),A)[+Wb>>>2>>>0];Wb+=4;return a},Xb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},O=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Xb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Yb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},P=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Zb=(a,b)=>O(a+"/"+b),$b=()=>{if(p){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>b.set(crypto.getRandomValues(new Uint8Array(b.byteLength)))},ac=a=>{(ac=$b())(a)},bc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:F.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Xb(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},cc=(a,b)=>{function c(h){for(var l=0;l<h.length&&""===h[l];l++);for(var n=h.length-1;0<=n&&""===h[n];n--);return l>n?[]:h.slice(l,n-l+1)}a=bc(a).slice(1);b=bc(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},dc=globalThis.TextDecoder&&new TextDecoder,Q=(a,b=0)=>{b>>>=0;var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;
if(16<c-b&&a.buffer&&dc)return dc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},ec=[],fc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},gc=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++>>>0]=h}else if(2047>=h){if(c+1>=d)break;b[c++>>>0]=192|h>>6;b[c++>>>0]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++>>>0]=224|h>>12;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63}else{if(c+3>=d)break;b[c++>>>0]=240|h>>18;b[c++>>>0]=128|h>>12&63;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63;g++}}b[c>>>
0]=0;return c-e},hc=a=>{var b=Array(fc(a)+1);a=gc(a,b,0,b.length);b.length=a;return b},ic=[];function jc(a,b){ic[a]={input:[],output:[],J:b};kc(a,lc)}
var lc={open(a){var b=ic[a.node.rdev];if(!b)throw new F.g(43);a.tty=b;a.seekable=!1},close(a){a.tty.J.fsync(a.tty)},fsync(a){a.tty.J.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.J.na)throw new F.g(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.J.na(a.tty)}catch(l){throw new F.g(29);}if(void 0===h&&0===e)throw new F.g(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.J.ia)throw new F.g(60);try{for(var e=0;e<d;e++)a.tty.J.ia(a.tty,b[c+
e])}catch(g){throw new F.g(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},mc={na(){a:{if(!ec.length){var a=null;if(p){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ec=hc(a)}a=ec.shift()}return a},ia(a,b){null===b||10===b?(qa(Q(a.output)),a.output=[]):0!=b&&a.output.push(b)},
fsync(a){0<a.output?.length&&(qa(Q(a.output)),a.output=[])},La(){return{fb:25856,hb:5,eb:191,gb:35387,cb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ma(){return 0},Na(){return[24,80]}},nc={ia(a,b){null===b||10===b?(u(Q(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(u(Q(a.output)),a.output=[])}},R={F:null,l(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||F.isFIFO(c))throw new F.g(63);R.F||(R.F={dir:{node:{v:R.h.v,
C:R.h.C,lookup:R.h.lookup,H:R.h.H,rename:R.h.rename,unlink:R.h.unlink,rmdir:R.h.rmdir,readdir:R.h.readdir,symlink:R.h.symlink},stream:{o:R.i.o}},file:{node:{v:R.h.v,C:R.h.C},stream:{o:R.i.o,read:R.i.read,write:R.i.write,P:R.i.P,S:R.i.S}},link:{node:{v:R.h.v,C:R.h.C,readlink:R.h.readlink},stream:{}},ja:{node:{v:R.h.v,C:R.h.C},stream:F.Da}});c=F.createNode(a,b,c,d);S(c.mode)?(c.h=R.F.dir.node,c.i=R.F.dir.stream,c.j={}):F.isFile(c.mode)?(c.h=R.F.file.node,c.i=R.F.file.stream,c.m=0,c.j=null):40960===
(c.mode&61440)?(c.h=R.F.link.node,c.i=R.F.link.stream):8192===(c.mode&61440)&&(c.h=R.F.ja.node,c.i=R.F.ja.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.j[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},sb(a){return a.j?a.j.subarray?a.j.subarray(0,a.m):new Uint8Array(a.j):new Uint8Array(0)},h:{v(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;S(a.mode)?b.size=4096:F.isFile(a.mode)?b.size=a.m:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},C(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.m!=b&&(0==b?(a.j=null,a.m=0):(c=a.j,a.j=new Uint8Array(b),c&&a.j.set(c.subarray(0,Math.min(b,a.m))),a.m=b)))},lookup(){R.Z||(R.Z=new F.g(44),R.Z.stack="<generic error, no stack>");throw R.Z;},H(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=
T(b,c)}catch(g){}if(d){if(S(a.mode))for(var e in d.j)throw new F.g(55);oc(d)}delete a.parent.j[a.name];b.j[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.j[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=T(a,b),d;for(d in c.j)throw new F.g(55);delete a.j[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.j)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new F.g(28);return a.link}},
i:{read(a,b,c,d,e){var g=a.node.j;if(e>=a.node.m)return 0;a=Math.min(a.node.m-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===(w(),z).buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.j||a.j.subarray)){if(g)return a.j=b.subarray(c,c+d),a.m=d;if(0===a.m&&0===e)return a.j=b.slice(c,c+d),a.m=d;if(e+d<=a.m)return a.j.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.j?a.j.length:0;h>=g||(g=Math.max(g,
h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.j,a.j=new Uint8Array(g),0<a.m&&a.j.set(h.subarray(0,a.m),0));if(a.j.subarray&&b.subarray)a.j.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.j[e+g]=b[c+g];a.m=Math.max(a.m,e+d);return d},o(a,b,c){1===c?b+=a.position:2===c&&F.isFile(a.node.mode)&&(b+=a.node.m);if(0>b)throw new F.g(28);return b},P(a,b,c,d,e){if(!F.isFile(a.node.mode))throw new F.g(43);a=a.node.j;if(e&2||!a||a.buffer!==(w(),z).buffer){d=!0;I();e=void 0;if(!e)throw new F.g(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(w(),z).set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{yb:e,Za:d}},S(a,b,c,d){R.i.write(a,b,0,d,c,!1);return 0}}},pc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qc=async a=>{a=await ia(a);return new Uint8Array(a)},rc=[],sc=async(a,b)=>{"undefined"!=typeof Browser&&Browser.V();for(var c of rc)if(c.canHandle(b))return c.handle(a,b);return a},tc=async(a,b,c,d,e,g,h,l)=>{var n=b?bc(O(a+"/"+b)):a;J++;try{var k=
c;"string"==typeof c&&(k=await qc(c));k=await sc(k,n);l?.();if(!g){c=b;a&&(a="string"==typeof a?a:U(a),c=b?O(a+"/"+b):a);var q=pc(d,e),v=F.create(c,q);if(k){if("string"==typeof k){var H=Array(k.length);b=0;for(var B=k.length;b<B;++b)H[b]=k.charCodeAt(b);k=H}F.chmod(v,q|146);var x=F.open(v,577);F.write(x,k,0,k.length,0,h);F.close(x);F.chmod(v,q)}}}finally{Mb()}};function kc(a,b){F.la[a]={i:b}}function S(a){return 16384===(a&61440)}
function T(a,b){var c=S(a.mode)?(c=V(a,"x"))?c:a.h.lookup?0:2:54;if(c)throw new F.g(c);for(c=F.I[uc(a.id,b)];c;c=c.O){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return F.lookup(a,b)}function oc(a){var b=uc(a.parent.id,a.name);if(F.I[b]===a)F.I[b]=a.O;else for(b=F.I[b];b;){if(b.O===a){b.O=a.O;break}b=b.O}}
function W(a,b={}){if(!a)throw new F.g(44);b.U??(b.U=!0);"/"===a.charAt(0)||(a=F.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=F.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Yb(e),F.fa(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=O(e+"/"+a[g]);try{d=T(d,a[g])}catch(l){if(44===l?.s&&h&&b.Qa)return{path:e};throw l;}!d.A||h&&!b.U||(d=d.A.root);if(40960===(d.mode&61440)&&(!h||b.u)){if(!d.h.readlink)throw new F.g(52);
d=d.h.readlink(d);"/"===d.charAt(0)||(d=Yb(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new F.g(32);}function U(a){for(var b;;){if(F.fa(a))return a=a.l.ta,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function uc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%F.I.length}function vc(a){var b=uc(a.parent.id,a.name);a.O=F.I[b];F.I[b]=a}
function wc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function V(a,b){if(F.oa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function xc(a,b){if(!S(a.mode))return 54;try{return T(a,b),20}catch(c){}return V(a,"wx")}
function yc(a,b,c){try{var d=T(a,b)}catch(e){return e.s}if(a=V(a,"wx"))return a;if(c){if(!S(d.mode))return 54;if(F.fa(d)||U(d)===F.cwd())return 10}else if(S(d.mode))return 31;return 0}function zc(a,b){if(!a)throw new F.g(b);return a}function X(a){a=F.Ia(a);if(!a)throw new F.g(8);return a}function Ac(a,b=-1){a=Object.assign(new F.Ba,a);if(-1==b)a:{for(b=0;b<=F.Ca;b++)if(!F.streams[b])break a;throw new F.g(33);}a.fd=b;return F.streams[b]=a}function Bc(a,b=-1){a=Ac(a,b);a.i?.mb?.(a);return a}
function Cc(a,b,c){var d=a?.i.C;a=d?a:b;d??=b.h.C;zc(d,63);d(a,c)}function Dc(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.R)}return b}function Ec(a){var b={bb:4096,pb:4096,blocks:1E6,ab:5E5,$a:5E5,files:F.ha,nb:F.ha-1,qb:42,flags:2,wb:255};a.h.va&&Object.assign(b,a.h.va(a.l.Sa.root));return b}function Fc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return F.H(a,b|8192,c)}function Gc(a,b,c,d){Cc(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),ma:d})}
function Hc(a,b,c){if(S(b.mode))throw new F.g(31);if(!F.isFile(b.mode))throw new F.g(28);var d=V(b,"w");if(d)throw new F.g(d);Cc(a,b,{size:c,timestamp:Date.now()})}function Ic(a,b,c,d){a="string"==typeof a?a:U(a);b=O(a+"/"+b);return F.create(b,pc(c,d))}
function Jc(a){if(!(a.Oa||a.Pa||a.link||a.j))if(globalThis.XMLHttpRequest)I("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.j=ja(a.url)}catch(b){throw new F.g(29);}}
var F={root:null,R:[],la:{},streams:[],ha:1,I:null,ka:"/",da:!1,oa:!0,Ga:null,W:0,g:class{name="ErrnoError";constructor(a){this.s=a}},Ba:class{G={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.G.flags}set flags(a){this.G.flags=a}get position(){return this.G.position}set position(a){this.G.position=a}},Aa:class{h={};i={};A=null;constructor(a,b,c,d){a||=this;this.parent=a;this.l=a.l;this.id=F.ha++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=
this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Pa(){return S(this.mode)}get Oa(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new F.Aa(a,b,c,d);vc(a);return a},fa(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Ca:4096,Ia:a=>F.streams[a],Da:{open(a){a.i=
F.Ha(a.node.rdev).i;a.i.open?.(a)},o(){throw new F.g(70);}},ga:a=>a>>8,ub:a=>a&255,N:(a,b)=>a<<8|b,Ha:a=>F.la[a],wa(a,b){function c(l){F.W--;return b(l)}function d(l){if(l){if(!d.Fa)return d.Fa=!0,c(l)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);F.W++;1<F.W&&u(`warning: ${F.W} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Dc(F.root.l),g=0,h;for(h of e)h.type.wa?h.type.wa(h,a,d):d(null)},l(a,b,c){var d="/"===c;if(d&&F.root)throw new F.g(10);if(!d&&c){var e=
W(c,{U:!1});c=e.path;e=e.node;if(e.A)throw new F.g(10);if(!S(e.mode))throw new F.g(54);}b={type:a,Sa:b,ta:c,R:[]};a=a.l(b);a.l=b;b.root=a;d?F.root=a:e&&(e.A=b,e.l&&e.l.R.push(b));return a},Cb(a){a=W(a,{U:!1});if(!a.node.A)throw new F.g(28);a=a.node;var b=a.A,c=Dc(b);for([,e]of Object.entries(F.I))for(;e;){var d=e.O;c.includes(e.l)&&oc(e);var e=d}a.A=null;a.l.R.splice(a.l.R.indexOf(b),1)},lookup(a,b){return a.h.lookup(a,b)},H(a,b,c){var d=W(a,{parent:!0}).node;a=P(a);if(!a)throw new F.g(28);if("."===
a||".."===a)throw new F.g(20);var e=xc(d,a);if(e)throw new F.g(e);if(!d.h.H)throw new F.g(63);return d.h.H(d,a,b,c)},va(a){return Ec(W(a,{u:!0}).node)},Ab(a){return Ec(a.node)},create(a,b=438){return F.H(a,b&4095|32768,0)},mkdir(a,b=511){return F.H(a,b&1023|16384,0)},vb(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{F.mkdir(d,b)}catch(g){if(20!=g.s)throw g;}}},symlink(a,b){if(!bc(a))throw new F.g(44);var c=W(b,{parent:!0}).node;if(!c)throw new F.g(44);b=P(b);
var d=xc(c,b);if(d)throw new F.g(d);if(!c.h.symlink)throw new F.g(63);return c.h.symlink(c,b,a)},rename(a,b){var c=Yb(a),d=Yb(b),e=P(a),g=P(b);var h=W(a,{parent:!0});var l=h.node;h=W(b,{parent:!0});h=h.node;if(!l||!h)throw new F.g(44);if(l.l!==h.l)throw new F.g(75);var n=T(l,e);a=cc(a,d);if("."!==a.charAt(0))throw new F.g(28);a=cc(b,c);if("."!==a.charAt(0))throw new F.g(55);try{var k=T(h,g)}catch(q){}if(n!==k){b=S(n.mode);if(e=yc(l,e,b))throw new F.g(e);if(e=k?yc(h,g,b):xc(h,g))throw new F.g(e);if(!l.h.rename)throw new F.g(63);
if(n.A||k&&k.A)throw new F.g(10);if(h!==l&&(e=V(l,"w")))throw new F.g(e);oc(n);try{l.h.rename(n,h,g),n.parent=h}catch(q){throw q;}finally{vc(n)}}},rmdir(a){var b=W(a,{parent:!0}).node;a=P(a);var c=T(b,a),d=yc(b,a,!0);if(d)throw new F.g(d);if(!b.h.rmdir)throw new F.g(63);if(c.A)throw new F.g(10);b.h.rmdir(b,a);oc(c)},readdir(a){a=W(a,{u:!0}).node;return zc(a.h.readdir,54)(a)},unlink(a){var b=W(a,{parent:!0}).node;if(!b)throw new F.g(44);a=P(a);var c=T(b,a),d=yc(b,a,!1);if(d)throw new F.g(d);if(!b.h.unlink)throw new F.g(63);
if(c.A)throw new F.g(10);b.h.unlink(b,a);oc(c)},readlink(a){a=W(a).node;if(!a)throw new F.g(44);if(!a.h.readlink)throw new F.g(28);return a.h.readlink(a)},stat(a,b){a=W(a,{u:!b}).node;return zc(a.h.v,63)(a)},fstat(a){var b=X(a);a=b.node;var c=b.i.v;b=c?b:a;c??=a.h.v;zc(c,63);return c(b)},lstat(a){return F.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?W(a,{u:!c}).node:a;Gc(null,a,b,c)},lchmod(a,b){F.chmod(a,b,!0)},fchmod(a,b){a=X(a);Gc(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?W(a,{u:!d}).node:
a;Cc(null,a,{timestamp:Date.now(),ma:d})},lchown(a,b,c){F.chown(a,b,c,!0)},fchown(a){a=X(a);Cc(a,a.node,{timestamp:Date.now(),ma:!1})},truncate(a,b){if(0>b)throw new F.g(28);a="string"==typeof a?W(a,{u:!0}).node:a;Hc(null,a,b)},rb(a,b){a=X(a);if(0>b||0===(a.flags&2097155))throw new F.g(28);Hc(a,a.node,b)},Db(a,b,c){a=W(a,{u:!0}).node;zc(a.h.C,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new F.g(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==
typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=W(a,{u:!(b&131072),Qa:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new F.g(20);}else{if(e)throw new F.g(31);d=F.H(a,c|511,0);g=!0}if(!d)throw new F.g(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!S(d.mode))throw new F.g(54);if(!g&&(e=d?40960===(d.mode&61440)?32:S(d.mode)&&("r"!==wc(b)||b&576)?31:V(d,wc(b)):44))throw new F.g(e);b&512&&!g&&F.truncate(d,
0);b&=-131713;b=Ac({node:d,path:U(d),flags:b,seekable:!0,position:0,i:d.i,Wa:[],error:!1});b.i.open&&b.i.open(b);g&&F.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new F.g(8);a.$&&(a.$=null);try{a.i.close&&a.i.close(a)}catch(b){throw b;}finally{F.streams[a.fd]=null}a.fd=null},o(a,b,c){if(null===a.fd)throw new F.g(8);if(!a.seekable||!a.i.o)throw new F.g(70);if(0!=c&&1!=c&&2!=c)throw new F.g(28);a.position=a.i.o(a,b,c);a.Wa=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new F.g(28);
if(null===a.fd)throw new F.g(8);if(1===(a.flags&2097155))throw new F.g(8);if(S(a.node.mode))throw new F.g(31);if(!a.i.read)throw new F.g(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F.g(70);b=a.i.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new F.g(28);if(null===a.fd)throw new F.g(8);if(0===(a.flags&2097155))throw new F.g(8);if(S(a.node.mode))throw new F.g(31);if(!a.i.write)throw new F.g(28);a.seekable&&a.flags&1024&&F.o(a,0,
2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new F.g(70);b=a.i.write(a,b,c,d,e,g);h||(a.position+=b);return b},P(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new F.g(2);if(1===(a.flags&2097155))throw new F.g(2);if(!a.i.P)throw new F.g(43);if(!b)throw new F.g(28);return a.i.P(a,b,c,d,e)},S(a,b,c,d,e){return a.i.S?a.i.S(a,b,c,d,e):0},ea(a,b,c){if(!a.i.ea)throw new F.g(59);return a.i.ea(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||
"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&I(`Invalid encoding type "${b.encoding}"`);var c=F.open(a,b.flags);a=F.stat(a).size;var d=new Uint8Array(a);F.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Q(d));F.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=F.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(hc(b)));ArrayBuffer.isView(b)?F.write(a,b,0,b.byteLength,void 0,c.ib):I("Unsupported data type");F.close(a)},cwd:()=>F.ka,chdir(a){a=W(a,{u:!0});if(null===a.node)throw new F.g(44);
if(!S(a.node.mode))throw new F.g(54);var b=V(a.node,"x");if(b)throw new F.g(b);F.ka=a.path},V(a,b,c){F.da=!0;a?F.M("/dev","stdin",a):F.symlink("/dev/tty","/dev/stdin");b?F.M("/dev","stdout",null,b):F.symlink("/dev/tty","/dev/stdout");c?F.M("/dev","stderr",null,c):F.symlink("/dev/tty1","/dev/stderr");F.open("/dev/stdin",0);F.open("/dev/stdout",1);F.open("/dev/stderr",1)},zb(){F.da=!1;for(var a of F.streams)a&&F.close(a)},ob(a,b){try{var c=W(a,{u:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=W(a,{parent:!0}),
P(a),c=W(a,{u:!b}),d=!0,e=c.node}catch(g){}return d?e:null},kb(a,b){a="string"==typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=O(a+"/"+c);try{F.mkdir(d)}catch(e){if(20!=e.s)throw e;}a=d}}return d},M(a,b,c,d){a=Zb("string"==typeof a?a:U(a),b);b=pc(!!c,!!d);var e;(e=F.M).ga??(e.ga=64);e=F.N(F.M.ga++,0);kc(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,l,n){for(var k=0,q=0;q<n;q++){try{var v=c()}catch(H){throw new F.g(29);}if(void 0===v&&0===k)throw new F.g(6);
if(null===v||void 0===v)break;k++;h[l+q]=v}k&&(g.node.atime=Date.now());return k},write(g,h,l,n){for(var k=0;k<n;k++)try{d(h[l+k])}catch(q){throw new F.g(29);}n&&(g.node.mtime=g.node.ctime=Date.now());return k}});return Fc(a,b,e)},jb(a,b,c,d,e){class g{ba=!1;G=[];aa=void 0;qa=0;pa=0;get(k){if(!(k>this.length-1||0>k)){var q=k%this.chunkSize;return this.aa(k/this.chunkSize|0)[q]}}Ra(k){this.aa=k}sa(){var k=new XMLHttpRequest;k.open("HEAD",c,!1);k.send(null);200<=k.status&&300>k.status||304===k.status||
I("Couldn't load "+c+". Status: "+k.status);var q=Number(k.getResponseHeader("Content-length")),v,H=(v=k.getResponseHeader("Accept-Ranges"))&&"bytes"===v;k=(v=k.getResponseHeader("Content-Encoding"))&&"gzip"===v;var B=1048576;H||(B=q);var x=this;x.Ra(Z=>{var la=Z*B,aa=(Z+1)*B-1;aa=Math.min(aa,q-1);if("undefined"==typeof x.G[Z]){var Sc=x.G;la>aa&&I("invalid range ("+la+", "+aa+") or no bytes requested!");aa>q-1&&I("only "+q+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",
c,!1);q!==B&&E.setRequestHeader("Range","bytes="+la+"-"+aa);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);200<=E.status&&300>E.status||304===E.status||I("Couldn't load "+c+". Status: "+E.status);la=void 0!==E.response?new Uint8Array(E.response||[]):hc(E.responseText||"");Sc[Z]=la}"undefined"==typeof x.G[Z]&&I("doXHR failed!");return x.G[Z]});if(k||!q)B=q=1,B=q=this.aa(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");
this.qa=q;this.pa=B;this.ba=!0}get length(){this.ba||this.sa();return this.qa}get chunkSize(){this.ba||this.sa();return this.pa}}if(globalThis.XMLHttpRequest){m||I("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var l=void 0}else l=c,h=void 0;var n=Ic(a,b,d,e);h?n.j=h:l&&(n.j=null,n.url=l);Object.defineProperties(n,{m:{get:function(){return this.j.length}}});a={};for(const [k,q]of Object.entries(n.i))a[k]=(...v)=>{Jc(n);
return q(...v)};a.read=(k,q,v,H,B)=>{Jc(n);k=k.node.j;if(B>=k.length)q=0;else{H=Math.min(k.length-B,H);if(k.slice)for(var x=0;x<H;x++)q[v+x]=k[B+x];else for(x=0;x<H;x++)q[v+x]=k.get(B+x);q=H}return q};a.P=()=>{Jc(n);I();throw new F.g(48);};n.i=a;return n}},Kc=a=>(a>>>=0)?Q((w(),Ja),a):"",Wb=void 0;
function Va(a,b,c){if(r)return L(3,1,a,b,c);Wb=c>>>0;try{var d=X(a);switch(b){case 0:var e=N();if(0>e)break;for(;F.streams[e];)e++;return Bc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=N(),d.flags|=e,0;case 12:return e=N(),(w(),Ka)[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return-g.s}}var Y=(a,b,c)=>gc(a,(w(),Ja),b,c);
function Wa(a,b){if(r)return L(4,1,a,b);b>>>=0;try{if(0===b)return-28;var c=F.cwd(),d=fc(c)+1;if(b<d)return-68;Y(c,a>>>0,b);return d}catch(e){if("undefined"==typeof F||"ErrnoError"!==e.name)throw e;return-e.s}}
function Xa(a,b,c){if(r)return L(5,1,a,b,c);Wb=c>>>0;try{var d=X(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.J.La){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=N();(w(),A)[e>>>2>>>0]=25856;(w(),A)[e+4>>>2>>>0]=5;(w(),A)[e+8>>>2>>>0]=191;(w(),A)[e+12>>>2>>>0]=35387;for(var g=0;32>g;g++)(w(),z)[e+g+17>>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;
if(d.tty.J.Ma)for(e=N(),w(),w(),w(),w(),a=[],g=0;32>g;g++)a.push((w(),z)[e+g+17>>>0]);return 0;case 21519:if(!d.tty)return-59;e=N();return(w(),A)[e>>>2>>>0]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=N(),F.ea(d,b,e);case 21523:if(!d.tty)return-59;d.tty.J.Na&&(g=[24,80],e=N(),(w(),Ka)[e>>>1>>>0]=g[0],(w(),Ka)[e+2>>>1>>>0]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof F||"ErrnoError"!==h.name)throw h;
return-h.s}}function Ya(a,b,c,d){if(r)return L(6,1,a,b,c,d);b>>>=0;Wb=d>>>=0;try{b=Kc(b);var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?F.cwd():X(a).path;if(0==e.length)throw new F.g(44);b=g+"/"+e}var h=d?N():0;return F.open(b,c,h).fd}catch(l){if("undefined"==typeof F||"ErrnoError"!==l.name)throw l;return-l.s}}var Za=()=>I("");function $a(a){Da(a>>>0,!m,1,!ba,67108864,!1);Ea()}
var Lc=a=>{a instanceof Ib||"unwind"==a||fa(1,a)},Sb=a=>{if(!sa)try{if(a(),!(M||0<K))try{r?xb()&&Ab(ta):pb(ta)}catch(b){Lc(b)}}catch(b){Lc(b)}},Mc=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]);function Fa(a){a>>>=0;Mc||(Atomics.waitAsync((w(),A),a>>>2,a).value.then(Ha),a+=128,Atomics.store((w(),A),a>>>2,1))}var Ha=()=>Sb(()=>{var a=xb();a&&(Fa(a),Cb())});
function ab(a,b){a>>>=0;a==b>>>0?setTimeout(Ha):r?postMessage({X:a,D:"checkMailbox"}):(a=t.K[a])&&a.postMessage({D:"checkMailbox"})}var Nc=[];function bb(a,b,c,d,e){c>>>=0;d/=2;Nc.length=d;b=e>>>0>>>3;for(e=0;e<d;e++)(w(),D)[b+2*e>>>0]?Nc[e]=(w(),D)[b+2*e+1>>>0]:Nc[e]=(w(),La)[b+2*e+1>>>0];a=Oc[a];t.Ea=c;c=a(...Nc);t.Ea=0;return c}var cb=()=>{M=!1;K=0};function db(a){a>>>=0;r?postMessage({D:"cleanupThread",Va:a}):t.ua(t.K[a])}function eb(a){p&&t.K[a>>>0].ref()}
var Pc={},lb=()=>performance.timeOrigin+performance.now();function fb(a,b){if(r)return L(7,1,a,b);Pc[a]&&(clearTimeout(Pc[a].id),delete Pc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Pc[a];Sb(()=>Bb(a,performance.timeOrigin+performance.now()))},b);Pc[a]={id:c,Bb:b};return 0}
function gb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var h=Math.max(g,e);(w(),C)[a>>>2>>>0]=60*h;(w(),A)[b>>>2>>>0]=Number(g!=e);b=l=>{var n=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(Y(a,c,17),Y(b,d,17)):(Y(a,d,17),Y(b,c,17))}var jb=()=>Date.now(),Qc=1;
function hb(a,b,c){c>>>=0;if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Qc)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(w(),D)[c>>>3>>>0]=BigInt(a);return 0}var ib=()=>{},kb=()=>{K+=1;throw"unwind";};
function mb(a){a>>>=0;var b=(w(),Ja).length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-y.buffer.byteLength+65535)/65536|0;try{y.grow(d);ua();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1}
var Rc={},Uc=()=>{if(!Tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Rc)void 0===Rc[b]?delete a[b]:a[b]=Rc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Tc=c}return Tc},Tc;function nb(a,b){if(r)return L(8,1,a,b);a>>>=0;b>>>=0;var c=0,d=0,e;for(e of Uc()){var g=b+c;(w(),C)[a+d>>>2>>>0]=g;c+=Y(e,g,Infinity)+1;d+=4}return 0}
function ob(a,b){if(r)return L(9,1,a,b);a>>>=0;b>>>=0;var c=Uc();(w(),C)[a>>>2>>>0]=c.length;a=0;for(var d of c)a+=fc(d)+1;(w(),C)[b>>>2>>>0]=a;return 0}function qb(a){if(r)return L(10,1,a);try{var b=X(a);F.close(b);return 0}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return c.s}}
function rb(a,b,c,d){if(r)return L(11,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;try{a:{var e=X(a);a=b;for(var g,h=b=0;h<c;h++){var l=(w(),C)[a>>>2>>>0],n=(w(),C)[a+4>>>2>>>0];a+=8;var k=F.read(e,(w(),z),l,n,g);if(0>k){var q=-1;break a}b+=k;if(k<n)break;"undefined"!=typeof g&&(g+=k)}q=b}(w(),C)[d>>>2>>>0]=q;return 0}catch(v){if("undefined"==typeof F||"ErrnoError"!==v.name)throw v;return v.s}}
function sb(a,b,c,d){if(r)return L(12,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;var e=X(a);F.o(e,b,c);(w(),D)[d>>>3>>>0]=BigInt(e.position);e.$&&0===b&&0===c&&(e.$=null);return 0}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return g.s}}
function tb(a,b,c,d){if(r)return L(13,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;try{a:{var e=X(a);a=b;for(var g,h=b=0;h<c;h++){var l=(w(),C)[a>>>2>>>0],n=(w(),C)[a+4>>>2>>>0];a+=8;var k=F.write(e,(w(),z),l,n,g);if(0>k){var q=-1;break a}b+=k;if(k<n)break;"undefined"!=typeof g&&(g+=k)}q=b}(w(),C)[d>>>2>>>0]=q;return 0}catch(v){if("undefined"==typeof F||"ErrnoError"!==v.name)throw v;return v.s}}var Vc=a=>{var b=fc(a)+1,c=Fb(b);Y(a,c,b);return c};t.V();F.lb=(a,b,c,d,e,g,h,l,n,k)=>{tc(a,b,c,d,e,l,n,k).then(g).catch(h)};
F.xb=tc;F.I=Array(4096);F.l(R,{},"/");F.mkdir("/tmp");F.mkdir("/home");F.mkdir("/home/web_user");(function(){F.mkdir("/dev");kc(F.N(1,3),{read:()=>0,write:(d,e,g,h)=>h,o:()=>0});Fc("/dev/null",F.N(1,3));jc(F.N(5,0),mc);jc(F.N(6,0),nc);Fc("/dev/tty",F.N(5,0));Fc("/dev/tty1",F.N(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(ac(a),b=a.byteLength);return a[--b]};F.M("/dev","random",c);F.M("/dev","urandom",c);F.mkdir("/dev/shm");F.mkdir("/dev/shm/tmp")})();
(function(){F.mkdir("/proc");var a=F.mkdir("/proc/self");F.mkdir("/proc/self/fd");F.l({l(){var b=F.createNode(a,"fd",16895,73);b.i={o:R.i.o};b.h={lookup(c,d){c=+d;var e=X(c);c={parent:null,l:{ta:"fake"},h:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(F.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();F.Ga={MEMFS:R};r||(y=new WebAssembly.Memory({initial:1408,maximum:65536,shared:!0}),ua());f.noExitRuntime&&(M=f.noExitRuntime);
f.print&&(qa=f.print);f.ccall=(a,b,c,d)=>{var e={string:k=>{var q=0;null!==k&&void 0!==k&&0!==k&&(q=Vc(k));return q},array:k=>{var q=Fb(k.length);(w(),z).set(k,q>>>0);return q}};a=f["_"+a];var g=[],h=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===h&&(h=Gb()),g[l]=n(d[l])):g[l]=d[l]}c=a(...g);return c=function(k){0!==h&&Eb(h);return"string"===b?Kc(k):"pointer"===b?k>>>0:"boolean"===b?!!k:k}(c)};f.FS=F;f.PThread=t;
var Oc=[ub,Pb,Vb,Va,Wa,Xa,Ya,fb,nb,ob,qb,rb,sb,tb],wb,xb,Da,Ia,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ta;function vb(){var a=G;a=Object.assign({},a);var b=c=>()=>c()>>>0;a.pthread_self=b(a.pthread_self);a._emscripten_stack_alloc=(c=>d=>c(d)>>>0)(a._emscripten_stack_alloc);a.emscripten_stack_get_current=b(a.emscripten_stack_get_current);return a}
function Wc(a=[]){var b=wb;a.unshift(ea);var c=a.length,d=Fb(4*(c+1)),e=d,g;for(g of a)(w(),C)[e>>>2>>>0]=Vc(g),e+=4;(w(),C)[e>>>2>>>0]=0;try{var h=b(c,d);pb(h,!0)}catch(l){Lc(l)}}function Ba(a=da){if(0<J)Lb=Ba;else if(r)va?.(f),Na();else{for(var b=Kb;0<b.length;)b.shift()(f);if(0<J)Lb=Ba;else if(f.calledRun=!0,!sa&&(Na(),va?.(f),Wc(a),!r)){if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)a=f.postRun.shift(),Tb.push(a);for(a=Tb;0<a.length;)a.shift()(f)}}}var G;
r||(G=await (Aa()),Ba());Ma?moduleRtn=f:moduleRtn=new Promise((a,b)=>{va=a;wa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=YaneuraOu_K_P;module.exports.default=YaneuraOu_K_P}else if(typeof define==="function"&&define["amd"])define([],()=>YaneuraOu_K_P);var isPthread=globalThis.self?.name?.startsWith("em-pthread");var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=require("worker_threads").workerData==="em-pthread";isPthread&&YaneuraOu_K_P();
